DATAS SEGMENT
    ARRAY DB 61H, 84H, 93H, 0C4H, 17H, 0FFH, 52H, 2AH
    COUNT EQU ($-ARRAY) / TYPE ARRAY
DATAS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS
START:
    MOV AX,DATAS
    MOV DS,AX
    MOV CX,COUNT
    DEC CX
OUTLP:
    MOV DX,CX
    MOV BX,OFFSET ARRAY
INLP:
    MOV AL,[BX]
    CMP AL,[BX+1]
    JNG NEXT
    XCHG AL,[BX+1]
    MOV [BX],AL
NEXT:
    INC BX
    DEC DX
    JNZ INLP
    LOOP OUTLP
    MOV AH,4CH
    INT 21H
CODES ENDS
    END START

