DATAS SEGMENT
    ASCADDR db '0123456789'
    NUMBER  db 10
    BCDADDR db 20 DUP(?)
DATAS ENDS

CODES SEGMENT
    ASSUME CS:CODES,DS:DATAS
START:
    ;建立中断矢量表
    MOV AH,25H
    MOV AL,78H
    MOV DX,SEG ASC_TO_BCD
    MOV DS,DX
    MOV DX,OFFSET ASC_TO_BCD
    INT 21H
    ;执行程序
    INT 78H
    ;结束程序
    MOV AH,4CH
    INT 21H
ASC_TO_BCD PROC
    ;初始化段基址
    MOV AX,DATAS
    MOV DS,AX
    MOV SI,OFFSET ASCADDR
    MOV DI,OFFSET BCDADDR
    MOV CH,NUMBER
    SHR CH,1
    MOV CL,4
COUNT:
    MOV AX,[SI]
    AND AH,0FH
    SHL AL,CL
    OR  AH,AL
    MOV [DI],AH
    ADD SI,2
    INC DI
    DEC CH
    JNZ COUNT
    IRET
ASC_TO_BCD ENDP
CODES ENDS
    END START

